import type { Partner } from "./types";

const now = Date.now();

/** Seed partners — prices in сомони (what partner charges Jerib / sets in cabinet) */
export const SEED_PARTNERS: Partner[] = [
  {
    id: "p-dsb-atlas",
    name: "Atlas Print Dushanbe",
    cityId: "dushanbe",
    address: "ул. Рудаки 45, Душанбе",
    lat: 38.5731,
    lng: 68.785,
    serviceRadiusKm: 25,
    serviceCities: ["dushanbe"],
    acceptsRemoteDelivery: false,
    printMethods: ["dtg", "screen", "vinyl"],
    products: ["tshirt", "hoodie", "sweatshirt", "cap"],
    productionPrices: { tshirt: 90, hoodie: 180, sweatshirt: 140, cap: 55 },
    minOrderQty: 1,
    capacityUnits: 80,
    avgProductionHours: 18,
    workingHours: { open: 9, close: 20, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.35,
    rating: 4.7,
    qualityScore: 92,
    completionRate: 0.97,
    cancelRate: 0.02,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-dsb-silk",
    name: "Silk Press Studio",
    cityId: "dushanbe",
    address: "пр. Исмоили Сомони 12, Душанбе",
    lat: 38.5612,
    lng: 68.8021,
    serviceRadiusKm: 30,
    serviceCities: ["dushanbe", "kulob"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "embroidery", "sublimation"],
    products: ["tshirt", "hoodie", "sweatshirt", "pants"],
    productionPrices: { tshirt: 100, hoodie: 195, sweatshirt: 150, pants: 200 },
    minOrderQty: 1,
    capacityUnits: 60,
    avgProductionHours: 24,
    workingHours: { open: 10, close: 19, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.55,
    rating: 4.5,
    qualityScore: 88,
    completionRate: 0.94,
    cancelRate: 0.04,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-dsb-north",
    name: "North Gate Apparel",
    cityId: "dushanbe",
    address: "ул. Айни 88, Душанбе",
    lat: 38.548,
    lng: 68.76,
    serviceRadiusKm: 20,
    serviceCities: ["dushanbe"],
    acceptsRemoteDelivery: false,
    printMethods: ["screen", "vinyl", "dtg"],
    products: ["tshirt", "cap", "hoodie"],
    productionPrices: { tshirt: 85, hoodie: 170, cap: 50 },
    minOrderQty: 1,
    capacityUnits: 40,
    avgProductionHours: 14,
    workingHours: { open: 8, close: 18, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.8,
    rating: 4.2,
    qualityScore: 84,
    completionRate: 0.9,
    cancelRate: 0.06,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-khj-sughd",
    name: "Sughd Print Lab",
    cityId: "khujand",
    address: "ул. Ленина 21, Худжанд",
    lat: 40.285,
    lng: 69.618,
    serviceRadiusKm: 35,
    serviceCities: ["khujand"],
    acceptsRemoteDelivery: false,
    printMethods: ["dtg", "screen", "embroidery"],
    products: ["tshirt", "hoodie", "sweatshirt", "cap", "pants"],
    productionPrices: { tshirt: 88, hoodie: 175, sweatshirt: 135, cap: 52, pants: 190 },
    minOrderQty: 1,
    capacityUnits: 50,
    avgProductionHours: 20,
    workingHours: { open: 9, close: 19, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.4,
    rating: 4.6,
    qualityScore: 90,
    completionRate: 0.95,
    cancelRate: 0.03,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-khj-river",
    name: "Syr Darya Wear",
    cityId: "khujand",
    address: "ул. Камоли Хуҷандӣ 7, Худжанд",
    lat: 40.278,
    lng: 69.63,
    serviceRadiusKm: 40,
    serviceCities: ["khujand", "dushanbe"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "sublimation"],
    products: ["tshirt", "hoodie", "sweatshirt"],
    productionPrices: { tshirt: 95, hoodie: 185, sweatshirt: 145 },
    minOrderQty: 1,
    capacityUnits: 35,
    avgProductionHours: 22,
    workingHours: { open: 10, close: 20, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.25,
    rating: 4.4,
    qualityScore: 86,
    completionRate: 0.92,
    cancelRate: 0.05,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-klb-south",
    name: "Kulob Craft Print",
    cityId: "kulob",
    address: "ул. Борбад 3, Куляб",
    lat: 37.912,
    lng: 69.781,
    serviceRadiusKm: 30,
    serviceCities: ["kulob"],
    acceptsRemoteDelivery: false,
    printMethods: ["screen", "vinyl", "dtg"],
    products: ["tshirt", "hoodie", "cap"],
    productionPrices: { tshirt: 80, hoodie: 160, cap: 48 },
    minOrderQty: 1,
    capacityUnits: 25,
    avgProductionHours: 28,
    workingHours: { open: 9, close: 18, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.2,
    rating: 4.3,
    qualityScore: 85,
    completionRate: 0.91,
    cancelRate: 0.05,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
];
