import type { Partner } from "./types";

const now = Date.now();

/** Seed partners — production prices in local currency units */
export const SEED_PARTNERS: Partner[] = [
  {
    id: "p-us-atlas",
    name: "Atlas Print NYC",
    cityId: "us_new_york",
    address: "245 W 29th St, New York, NY",
    lat: 40.7484,
    lng: -73.994,
    serviceRadiusKm: 40,
    serviceCities: ["us_new_york", "us_philadelphia", "us_boston"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "screen", "vinyl"],
    products: ["tshirt", "hoodie", "sweatshirt", "cap"],
    productionPrices: { tshirt: 18, hoodie: 36, sweatshirt: 28, cap: 12 },
    minOrderQty: 1,
    capacityUnits: 80,
    avgProductionHours: 18,
    workingHours: { open: 9, close: 20, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.35,
    rating: 4.7,
    qualityScore: 92,
    completionRate: 0.97,
    cancelRate: 0.02,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-us-la",
    name: "Pacific Press Studio",
    cityId: "us_los_angeles",
    address: "1200 S Broadway, Los Angeles, CA",
    lat: 34.0407,
    lng: -118.256,
    serviceRadiusKm: 50,
    serviceCities: ["us_los_angeles", "us_san_diego", "us_las_vegas"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "embroidery", "sublimation"],
    products: ["tshirt", "hoodie", "sweatshirt", "pants"],
    productionPrices: { tshirt: 20, hoodie: 38, sweatshirt: 30, pants: 42 },
    minOrderQty: 1,
    capacityUnits: 60,
    avgProductionHours: 24,
    workingHours: { open: 10, close: 19, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.55,
    rating: 4.5,
    qualityScore: 88,
    completionRate: 0.94,
    cancelRate: 0.04,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-gb-london",
    name: "Thames Print Lab",
    cityId: "gb_london",
    address: "14 Brick Lane, London",
    lat: 51.5219,
    lng: -0.0717,
    serviceRadiusKm: 35,
    serviceCities: ["gb_london", "gb_birmingham", "gb_manchester"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "screen", "embroidery"],
    products: ["tshirt", "hoodie", "sweatshirt", "cap", "pants"],
    productionPrices: { tshirt: 16, hoodie: 32, sweatshirt: 26, cap: 10, pants: 38 },
    minOrderQty: 1,
    capacityUnits: 50,
    avgProductionHours: 20,
    workingHours: { open: 9, close: 19, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.4,
    rating: 4.6,
    qualityScore: 90,
    completionRate: 0.95,
    cancelRate: 0.03,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-de-berlin",
    name: "Berlin Silk Press",
    cityId: "de_berlin",
    address: "Torstraße 102, Berlin",
    lat: 52.529,
    lng: 13.401,
    serviceRadiusKm: 40,
    serviceCities: ["de_berlin", "de_hamburg", "de_leipzig"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "sublimation"],
    products: ["tshirt", "hoodie", "sweatshirt"],
    productionPrices: { tshirt: 17, hoodie: 34, sweatshirt: 27 },
    minOrderQty: 1,
    capacityUnits: 35,
    avgProductionHours: 22,
    workingHours: { open: 10, close: 20, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.25,
    rating: 4.4,
    qualityScore: 86,
    completionRate: 0.92,
    cancelRate: 0.05,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-fr-paris",
    name: "Atelier Print Paris",
    cityId: "fr_paris",
    address: "18 Rue de Rivoli, Paris",
    lat: 48.8566,
    lng: 2.3522,
    serviceRadiusKm: 30,
    serviceCities: ["fr_paris", "fr_lyon", "fr_marseille"],
    acceptsRemoteDelivery: false,
    printMethods: ["screen", "vinyl", "dtg"],
    products: ["tshirt", "cap", "hoodie"],
    productionPrices: { tshirt: 15, hoodie: 30, cap: 9 },
    minOrderQty: 1,
    capacityUnits: 40,
    avgProductionHours: 14,
    workingHours: { open: 8, close: 18, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.8,
    rating: 4.2,
    qualityScore: 84,
    completionRate: 0.9,
    cancelRate: 0.06,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-ca-toronto",
    name: "Maple Street Apparel",
    cityId: "ca_toronto",
    address: "220 Queen St W, Toronto",
    lat: 43.649,
    lng: -79.389,
    serviceRadiusKm: 45,
    serviceCities: ["ca_toronto", "ca_montreal", "ca_ottawa"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "screen", "vinyl"],
    products: ["tshirt", "hoodie", "cap"],
    productionPrices: { tshirt: 19, hoodie: 35, cap: 11 },
    minOrderQty: 1,
    capacityUnits: 25,
    avgProductionHours: 28,
    workingHours: { open: 9, close: 18, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.2,
    rating: 4.3,
    qualityScore: 85,
    completionRate: 0.91,
    cancelRate: 0.05,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
];
