import type { Partner } from "./types";

const now = Date.now();

/** Seed partners — production prices in сомони */
export const SEED_PARTNERS: Partner[] = [
  {
    id: "p-us-atlas",
    name: "Atlas Print",
    cityId: "tj_dushanbe",
    address: "ул. Рудаки 45, Душанбе",
    lat: 38.56,
    lng: 68.787,
    serviceRadiusKm: 25,
    serviceCities: ["tj_dushanbe", "tj_vahdat"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "screen", "vinyl"],
    products: ["tshirt", "hoodie", "sweatshirt", "cap"],
    productionPrices: { tshirt: 90, hoodie: 170, sweatshirt: 140, cap: 60 },
    minOrderQty: 1,
    capacityUnits: 80,
    avgProductionHours: 18,
    workingHours: { open: 9, close: 20, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.35,
    rating: 4.7,
    qualityScore: 92,
    completionRate: 0.97,
    cancelRate: 0.02,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-dsb-silk",
    name: "Silk Press",
    cityId: "tj_dushanbe",
    address: "пр. Исмоили Сомони 12, Душанбе",
    lat: 38.573,
    lng: 68.786,
    serviceRadiusKm: 20,
    serviceCities: ["tj_dushanbe"],
    acceptsRemoteDelivery: false,
    printMethods: ["dtg", "embroidery", "sublimation"],
    products: ["tshirt", "hoodie", "sweatshirt", "pants"],
    productionPrices: { tshirt: 85, hoodie: 165, sweatshirt: 135, pants: 190 },
    minOrderQty: 1,
    capacityUnits: 50,
    avgProductionHours: 20,
    workingHours: { open: 9, close: 19, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.45,
    rating: 4.5,
    qualityScore: 88,
    completionRate: 0.94,
    cancelRate: 0.04,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-khj-sughd",
    name: "Sughd Print",
    cityId: "tj_khujand",
    address: "ул. Ленина 21, Худжанд",
    lat: 40.283,
    lng: 69.622,
    serviceRadiusKm: 30,
    serviceCities: ["tj_khujand", "tj_istaravshan"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "screen", "vinyl"],
    products: ["tshirt", "hoodie", "sweatshirt", "cap", "pants"],
    productionPrices: { tshirt: 80, hoodie: 155, sweatshirt: 125, cap: 55, pants: 175 },
    minOrderQty: 1,
    capacityUnits: 45,
    avgProductionHours: 22,
    workingHours: { open: 9, close: 19, days: [1, 2, 3, 4, 5, 6] },
    currentLoad: 0.3,
    rating: 4.6,
    qualityScore: 90,
    completionRate: 0.95,
    cancelRate: 0.03,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
  {
    id: "p-tj-kulob",
    name: "Khatlon Print",
    cityId: "tj_kulob",
    address: "ул. Сомони 8, Куляб",
    lat: 37.914,
    lng: 69.785,
    serviceRadiusKm: 35,
    serviceCities: ["tj_kulob", "tj_bokhtar"],
    acceptsRemoteDelivery: true,
    printMethods: ["dtg", "screen"],
    products: ["tshirt", "hoodie", "cap"],
    productionPrices: { tshirt: 75, hoodie: 145, cap: 50 },
    minOrderQty: 1,
    capacityUnits: 30,
    avgProductionHours: 24,
    workingHours: { open: 9, close: 18, days: [1, 2, 3, 4, 5] },
    currentLoad: 0.2,
    rating: 4.3,
    qualityScore: 85,
    completionRate: 0.91,
    cancelRate: 0.05,
    acceptingOrders: true,
    approval: "approved",
    commissionOverride: null,
    createdAt: now,
  },
];
